### ISSUE TITLE
请问有打算让网站重新上线吗?

### ISSUE THREAD

**Issue by yizhiheng** [atonasting/zhihuspider#2]

**Comment by atonasting** [comment]
在知乎提问的也是你吗？确实不准备再上线了，可能会抽空写点别的程序，或者爬虫，但网站维护不想再做了。

**Comment by yizhiheng** [comment]
是我, 我挺想继续做你的工作...虽然如果有你的帮助的话可能会容易很多, 但是能理解你的决定, 确实是个很费时费力的工作.

请问域名你要留着吗? 能不能转给我? 因为工作的原因我可能不会开源程序, 如果你想再加入进来的话随时邀请.

**Comment by atonasting** [comment]
是准备商业应用？我还不会随意考虑出让域名和看知乎这个名字。不过如果你在开发中有一些想法可以随时沟通。

**Comment by yizhiheng** [comment]
不是商业目的, 我的目的可能和你一样..
好吧, 原本我是想继续让网站运行下去, 可能我会注册一个别的域名继续做吧.

谢谢回复.
